/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : TestDebugClass
 * Author          : <YourName>
 * Created Date    : Jan 29, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 29, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 29, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class TestDebugClass {

	@AuraEnabled(cacheable=true)
	public static void doSomething() {
		system.debug('test debug class');
	}

}